# Generated by Django 5.1.4 on 2024-12-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='status',
        ),
        migrations.RemoveField(
            model_name='player',
            name='two_FA',
        ),
    ]
