# Generated by Django 5.1.4 on 2024-12-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_player_avatar_url_remove_player_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar_url',
            field=models.URLField(default='https://media.tenor.com/zXRUDvNn0hIAAAAM/been-through-war.gif'),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ON', 'online'), ('OF', 'offline'), ('IG', 'in-game')], default='ON', max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='two_FA',
            field=models.BooleanField(default=False),
        ),
    ]
