# Generated by Django 5.1.4 on 2024-12-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_player_avatar_url_player_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
