# Generated by Django 5.1.4 on 2024-12-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_player_is_staff_remove_player_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
    ]
