# Generated by Django 5.1.4 on 2024-12-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_player_last_login_remove_player_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
    ]
