# Generated by Django 5.1.4 on 2025-01-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar_url',
            field=models.URLField(null=True),
        ),
    ]
